theme: minima
title: Qianruixi Wang
description: Bookmark this to keep an eye on my project updates!

header_pages:
  - about.md
  - experience.md
  - education.md
  - skills.md
  - projects.md
  - contact.md
